spring.datasource.url=jdbc:postgresql://localhost:5432/aura_db
spring.datasource.username=postgres
spring.datasource.password=2002*Five

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect